# Generated by Django 4.1.3 on 2022-11-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('uniqueName', models.TextField()),
                ('name', models.TextField()),
                ('gender', models.CharField(max_length=6)),
                ('age', models.PositiveSmallIntegerField()),
                ('motherTongue', models.TextField()),
                ('address', models.TextField()),
                ('hobby', models.TextField()),
                ('contactno', models.PositiveIntegerField()),
                ('emailaddress', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
